services:
  web:
    build: ./web
    ports:
      - "3001:3000"
    env_file: .env
    environment:
      - DIDCOMM_SERVICE_URL=http://didcomm:3000
      - RESOLVER_URL=http://uni-resolver-web:8080
    depends_on:
      - didcomm
      - uni-resolver-web

  didcomm:
    build: ./didcomm-http

  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    environment:
      uniresolver_web_driver_url_did_web: http://driver-did-uport:8081/

  driver-did-uport:
    image: uport/uni-resolver-driver-did-uport:latest
