services:
  web:
    build: ./web
    ports:
      - "3001:3000"
    env_file: .env
    environment:
      - DIDCOMM_SERVICE_URL=http://didcomm:3000
    volumes:
      - ./web/storage:/app/storage
    depends_on:
      - didcomm

  didcomm:
    image: onyxblade/didcomm-http:latest
